name: Train and Containerize

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  train_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn xgboost fastapi uvicorn prometheus-client "setuptools<70.0"

      - name: Fetch Preprocessed Data
        run: |
          mkdir -p ../Membangun_model/iris_preprocessing
          curl -o ../Membangun_model/iris_preprocessing/train.csv https://raw.githubusercontent.com/antsig/Model-SML/master/iris_preprocessing/train.csv
          curl -o ../Membangun_model/iris_preprocessing/test.csv https://raw.githubusercontent.com/antsig/Model-SML/master/iris_preprocessing/test.csv

      - name: Run mlflow project
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: "https://dagshub.com/antsig/Model-SML.mlflow"
          MLFLOW_TRACKING_USERNAME: "antsig"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: run_id
        run: |
          RUN_ID=$(cat MLProject/run_id.txt)
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install docker pydrive2

      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          echo "Uploading artifacts to Google Drive..."
          python scripts/upload_to_drive.py

      - name: Debug Directory Structure
        run: |
          echo "Workspace Directory Tree:"
          ls -laR

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/antsig/Model-SML.mlflow"
          MLFLOW_TRACKING_USERNAME: "antsig"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow models build-docker -m "MLProject/local_model" -n sml-model:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag sml-model:latest ${{ secrets.DOCKER_USERNAME }}/sml-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sml-model:latest
