name: Train and Containerize

on:
  push:
    paths:
      - "Workflow-CI/**"
  workflow_dispatch:

jobs:
  train_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn xgboost fastapi uvicorn prometheus-client setuptools<70.0

      - name: Configure DagsHub
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python -c "import dagshub; dagshub.init(repo_owner='antsig', repo_name='Model-SML', mlflow=True)"

      - name: Run MLProject
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/antsig/Model-SML.mlflow"
          MLFLOW_TRACKING_USERNAME: "antsig"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd Workflow-CI/MLProject
          mlflow run . -P param1=value --no-conda

      - name: Get latest MLflow run id
        id: run_id
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/antsig/Model-SML.mlflow"
          MLFLOW_TRACKING_USERNAME: "antsig"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Fetch the latest run generated by the MLProject
          RUN_ID=$(python -c '
          from mlflow.tracking import MlflowClient
          client = MlflowClient()
          exp = client.get_experiment_by_name("MLProject_Run")
          if exp:
              runs = client.search_runs(exp.experiment_id, order_by=["start_time desc"], max_results=1)
              if runs:
                  print(runs[0].info.run_id)
          ')
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV

      - name: Install Docker dependencies
        run: pip install docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/antsig/Model-SML.mlflow"
          MLFLOW_TRACKING_USERNAME: "antsig"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow models build-docker -m "runs:/${RUN_ID}/model" -n antsig/sml-model:latest

      - name: Push Docker Image
        run: docker push antsig/sml-model:latest
